name: Build MDPreviewer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:



jobs:
  build:
    name: Build and Test
    runs-on: macos-15 # Use macOS 15 which comes with Xcode 16 as default

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: |
        xcodegen generate

    - name: Resolve Package Dependencies
      run: |
        xcodebuild -resolvePackageDependencies -project MDPreviewer.xcodeproj -scheme MDPreviewer

    - name: List Targets and Schemes
      run: |
        xcodebuild -list -project MDPreviewer.xcodeproj

    - name: Build MDPreviewer
      run: |
        xcodebuild build -project MDPreviewer.xcodeproj -scheme MDPreviewer -destination 'platform=macOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""
